# trumpet_scales.py
# Generate all 12 written major scales (C–B) for B♭ trumpet using music21

from music21 import stream, note, key, instrument, scale, metadata

# All 12 written major keys for trumpet, moving chromatically from C
written_keys = ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B']

score = stream.Score()
score.metadata = metadata.Metadata(
    title="Major Scales for B♭ Trumpet (Written Keys C–B)",
    composer="Generated by music21"
)

for written_key_name in written_keys:
    # Create a part for each written key
    part = stream.Part()
    part.id = f"Trumpet_{written_key_name}"

    # Attach the instrument (as metadata, not a timed element)
    part.insert(0, instrument.Trumpet())

    # Written key (what the trumpet player reads)
    k = key.Key(written_key_name)

    # Apply key signature
    ks = key.KeySignature(k.sharps)
    part.append(ks)

    # Build one-octave MAJOR scale starting on the written key tonic
    # We'll use octave 4 → 5 for treble clef trumpet
    major = scale.MajorScale(written_key_name)

    pitches = major.getPitches(f"{written_key_name}4", f"{written_key_name}5")

    for p in pitches:
        n = note.Note(p)
        n.quarterLength = 1  # quarter-note scale
        part.append(n)

    # Spacer rest between scales
    r = note.Rest()
    r.quarterLength = 1
    part.append(r)

    # Add this part to the score
    score.append(part)

# Write to a MusicXML file (safe and viewer-agnostic)
output_path = "trumpet_scales.musicxml"
score.write("musicxml", fp=output_path)

print(f"Wrote {output_path} in the current folder.")